import "./styles/global.css";
import { Inter } from "next/font/google";
import logo from "../../public/logo.png";
// import NavBar from "../components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "oneToInfiniti",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/apple-touch-icon.png?v=4"],
    shortcut: ["/apple-touch-icon.png"],
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        {/* Include the Header component */}
        <main>{children}</main>
      </body>
    </html>
  );
}
